"""Apply backend integrity fixes for indexes, constraints, and datetime

Revision ID: 3685f210bf5f
Revises: bffe9b265bfb
Create Date: 2026-03-25 10:07:01.058318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3685f210bf5f'
down_revision: Union[str, Sequence[str], None] = 'bffe9b265bfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_broker_accounts_user_broker'), 'broker_accounts', type_='unique')
    op.create_unique_constraint('uq_broker_accounts_user_broker_client', 'broker_accounts', ['user_id', 'broker', 'broker_client_id'])
    op.create_index('ix_snapshot_user_date', 'daily_portfolio_snapshots', ['user_id', 'snapshot_date'], unique=False)
    op.alter_column('ledger_entries', 'entry_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index('ix_ledger_user_date', 'ledger_entries', ['user_id', 'entry_date'], unique=False)
    op.create_index('ix_rpnl_user_sell', 'realized_pnl', ['user_id', 'sell_date'], unique=False)
    op.create_index('ix_trades_user_date', 'trades', ['user_id', 'trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trades_user_date', table_name='trades')
    op.drop_index('ix_rpnl_user_sell', table_name='realized_pnl')
    op.drop_index('ix_ledger_user_date', table_name='ledger_entries')
    op.alter_column('ledger_entries', 'entry_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_index('ix_snapshot_user_date', table_name='daily_portfolio_snapshots')
    op.drop_constraint('uq_broker_accounts_user_broker_client', 'broker_accounts', type_='unique')
    op.create_unique_constraint(op.f('uq_broker_accounts_user_broker'), 'broker_accounts', ['user_id', 'broker'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
