"""Analytics engine refactor models

Revision ID: 47290ff83364
Revises: 3685f210bf5f
Create Date: 2026-04-08 00:39:06.135615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47290ff83364'
down_revision: Union[str, Sequence[str], None] = '3685f210bf5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_transactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('trade_id', sa.UUID(), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_transactions_timestamp'), 'cash_transactions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_cash_transactions_user_id'), 'cash_transactions', ['user_id'], unique=False)
    op.create_table('holding_lots',
    sa.Column('holding_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('trade_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holding_lots_holding_id'), 'holding_lots', ['holding_id'], unique=False)
    op.create_index('ix_holding_lots_user_holding', 'holding_lots', ['user_id', 'holding_id'], unique=False)
    op.add_column('daily_pnl', sa.Column('realized_pnl', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('daily_pnl', sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('daily_pnl', sa.Column('total_pnl', sa.Numeric(precision=18, scale=2), nullable=True))
    
    op.execute('UPDATE daily_pnl SET realized_pnl = pnl, unrealized_pnl = 0, total_pnl = pnl')
    
    op.alter_column('daily_pnl', 'realized_pnl', nullable=False)
    op.alter_column('daily_pnl', 'unrealized_pnl', nullable=False)
    op.alter_column('daily_pnl', 'total_pnl', nullable=False)
    
    op.drop_column('daily_pnl', 'pnl')
    op.add_column('daily_portfolio_snapshots', sa.Column('total_realized_pnl', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('daily_portfolio_snapshots', sa.Column('total_unrealized_pnl', sa.Numeric(precision=18, scale=2), nullable=True))
    
    op.add_column('trades', sa.Column('version', sa.Integer(), nullable=True))
    op.execute('UPDATE trades SET version = 1')
    op.alter_column('trades', 'version', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'version')
    op.drop_column('daily_portfolio_snapshots', 'total_unrealized_pnl')
    op.drop_column('daily_portfolio_snapshots', 'total_realized_pnl')
    op.add_column('daily_pnl', sa.Column('pnl', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False))
    op.drop_column('daily_pnl', 'total_pnl')
    op.drop_column('daily_pnl', 'unrealized_pnl')
    op.drop_column('daily_pnl', 'realized_pnl')
    op.drop_index('ix_holding_lots_user_holding', table_name='holding_lots')
    op.drop_index(op.f('ix_holding_lots_holding_id'), table_name='holding_lots')
    op.drop_table('holding_lots')
    op.drop_index(op.f('ix_cash_transactions_user_id'), table_name='cash_transactions')
    op.drop_index(op.f('ix_cash_transactions_timestamp'), table_name='cash_transactions')
    op.drop_table('cash_transactions')
    # ### end Alembic commands ###
