"""initial_schema

Revision ID: bffe9b265bfb
Revises: 
Create Date: 2026-03-10 22:01:37.763724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bffe9b265bfb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('exchange', sa.String(length=10), nullable=True),
    sa.Column('segment', sa.String(length=20), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruments_isin'), 'instruments', ['isin'], unique=True)
    op.create_index(op.f('ix_instruments_sector'), 'instruments', ['sector'], unique=False)
    op.create_index(op.f('ix_instruments_symbol'), 'instruments', ['symbol'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('bank_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_accounts_user_id'), 'bank_accounts', ['user_id'], unique=False)
    op.create_table('broker_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('broker', sa.String(length=50), nullable=False),
    sa.Column('broker_client_id', sa.String(length=100), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'broker', name='uq_broker_accounts_user_broker')
    )
    op.create_index(op.f('ix_broker_accounts_user_id'), 'broker_accounts', ['user_id'], unique=False)
    op.create_table('daily_pnl',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('segment', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'trade_date', 'segment', name='uq_daily_pnl_user_date_segment')
    )
    op.create_index(op.f('ix_daily_pnl_trade_date'), 'daily_pnl', ['trade_date'], unique=False)
    op.create_table('daily_portfolio_snapshots',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_invested', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_pnl', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cash_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'snapshot_date', name='uq_snapshot_user_date')
    )
    op.create_index(op.f('ix_daily_portfolio_snapshots_user_id'), 'daily_portfolio_snapshots', ['user_id'], unique=False)
    op.create_table('holding_tags',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('tag_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'instrument_id', 'tag_name', name='uq_holding_tags_user_instrument_tag')
    )
    op.create_index(op.f('ix_holding_tags_user_id'), 'holding_tags', ['user_id'], unique=False)
    op.create_table('fund_transactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('broker_account_id', sa.UUID(), nullable=False),
    sa.Column('bank_account_id', sa.UUID(), nullable=True),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('speed', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('transaction_ref', sa.String(length=100), nullable=True),
    sa.Column('initiated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fund_transactions_user_id'), 'fund_transactions', ['user_id'], unique=False)
    op.create_table('funds_balances',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('broker_account_id', sa.UUID(), nullable=False),
    sa.Column('available_margin', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('withdrawable_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('unsettled_credits', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('pledged_margin', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('used_margin', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_margin', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'broker_account_id', name='uq_funds_balances_user_broker')
    )
    op.create_index(op.f('ix_funds_balances_user_id'), 'funds_balances', ['user_id'], unique=False)
    op.create_table('holdings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('broker_account_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('ltp', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('pnl_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'broker_account_id', 'instrument_id', name='uq_holdings_user_broker_instrument')
    )
    op.create_index(op.f('ix_holdings_broker_account_id'), 'holdings', ['broker_account_id'], unique=False)
    op.create_index(op.f('ix_holdings_instrument_id'), 'holdings', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_holdings_user_id'), 'holdings', ['user_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('broker_account_id', sa.UUID(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('original_narration', sa.Text(), nullable=True),
    sa.Column('entry_type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('transaction_ref', sa.String(length=100), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_broker_account_id'), 'ledger_entries', ['broker_account_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_category'), 'ledger_entries', ['category'], unique=False)
    op.create_index(op.f('ix_ledger_entries_user_id'), 'ledger_entries', ['user_id'], unique=False)
    op.create_table('trades',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('broker_account_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('trade_type', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('trade_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('order_id', sa.String(length=100), nullable=True),
    sa.Column('segment', sa.String(length=20), nullable=False),
    sa.Column('charges', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_instrument_id'), 'trades', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_trades_trade_date'), 'trades', ['trade_date'], unique=False)
    op.create_index(op.f('ix_trades_user_id'), 'trades', ['user_id'], unique=False)
    op.create_table('realized_pnl',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('broker_account_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('buy_trade_id', sa.UUID(), nullable=True),
    sa.Column('sell_trade_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('buy_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('sell_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gross_pnl', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('charges', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('net_pnl', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('buy_date', sa.Date(), nullable=False),
    sa.Column('sell_date', sa.Date(), nullable=False),
    sa.Column('holding_period_days', sa.Integer(), nullable=True),
    sa.Column('tax_category', sa.String(length=10), nullable=True),
    sa.Column('financial_year', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ),
    sa.ForeignKeyConstraint(['buy_trade_id'], ['trades.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['sell_trade_id'], ['trades.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_realized_pnl_sell_date'), 'realized_pnl', ['sell_date'], unique=False)
    op.create_index(op.f('ix_realized_pnl_user_id'), 'realized_pnl', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_realized_pnl_user_id'), table_name='realized_pnl')
    op.drop_index(op.f('ix_realized_pnl_sell_date'), table_name='realized_pnl')
    op.drop_table('realized_pnl')
    op.drop_index(op.f('ix_trades_user_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_trade_date'), table_name='trades')
    op.drop_index(op.f('ix_trades_instrument_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_ledger_entries_user_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_category'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_broker_account_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_holdings_user_id'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_instrument_id'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_broker_account_id'), table_name='holdings')
    op.drop_table('holdings')
    op.drop_index(op.f('ix_funds_balances_user_id'), table_name='funds_balances')
    op.drop_table('funds_balances')
    op.drop_index(op.f('ix_fund_transactions_user_id'), table_name='fund_transactions')
    op.drop_table('fund_transactions')
    op.drop_index(op.f('ix_holding_tags_user_id'), table_name='holding_tags')
    op.drop_table('holding_tags')
    op.drop_index(op.f('ix_daily_portfolio_snapshots_user_id'), table_name='daily_portfolio_snapshots')
    op.drop_table('daily_portfolio_snapshots')
    op.drop_index(op.f('ix_daily_pnl_trade_date'), table_name='daily_pnl')
    op.drop_table('daily_pnl')
    op.drop_index(op.f('ix_broker_accounts_user_id'), table_name='broker_accounts')
    op.drop_table('broker_accounts')
    op.drop_index(op.f('ix_bank_accounts_user_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_instruments_symbol'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_sector'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_isin'), table_name='instruments')
    op.drop_table('instruments')
    # ### end Alembic commands ###
